[package]
name = "log-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0"
full_logger = "0.1.3"
tokio = "1.37.0"
pollster = "0.3.0"
eframe = "0.27.2"
