[package]
name = "log-server"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.1"
full_logger = "0.1.4"
tokio = "1.45.1"
pollster = "0.4.0"
eframe = "0.31.1"
